### ISSUE TITLE
Bug: Permissions from OIDC provider not applied

### ISSUE THREAD

**Issue by nr23730** [authup/authup#2395]
### Versions
- Docker container `ghcr.io/authup/authup:sha256:68dbcfe1200f1fdee8217188a14b014e859c1ebd4b1b80463497aba781899311`

### Steps to reproduce

1. Add OIDC Provider
2. Assign role "admin" in OIDC provider to authup-client
3. Create mapping in authup for "admin"
4. Try to login via OIDC provider.

### What is Expected?

Being logged with is role/permission `admin` assigned.

### What is actually happening?

Following error message is in the docker container log:

```
portal  | [nitro] [unhandledRejection] ClientError: The evaluation of permission user_read failed.
portal  |     at handleError (file:///usr/src/app/packages/portal/.output/server/node_modules/hapic/dist/index.mjs:720:23)
portal  |     at Client.request (file:///usr/src/app/packages/portal/.output/server/node_modules/hapic/dist/index.mjs:804:20)
portal  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
portal  |     at async UserInfoAPI.get (file:///usr/src/app/packages/portal/.output/server/node_modules/@hapic/oauth2/dist/index.mjs:338:26)
portal  |     at async resolveInternal (file:///usr/src/app/packages/portal/.output/server/node_modules/@authup/client-web-kit/dist/index.mjs:243:21) {
portal  |   code: undefined,
portal  |   expose: undefined,
portal  |   logMessage: undefined,
portal  |   logLevel: undefined,
portal  |   data: undefined,
portal  |   '@instanceof': Symbol(ClientError),
portal  |   request: {
portal  |     baseURL: 'http://authup:3000/',
portal  |     transform: [ [Function (anonymous)] ],
portal  |     headers: Headers {
portal  |       accept: 'application/json',
portal  |       Authorization: 'Bearer xyz'
portal  |     },
portal  |     method: 'GET',
portal  |     url: 'http://authup:3000/users/@me'
portal  |   },
portal  |   response: Response {
portal  |     status: 403,
portal  |     statusText: 'Forbidden',
portal  |     headers: Headers {
portal  |       vary: 'Origin',
portal  |       'access-control-allow-credentials': 'true',
portal  |       'ratelimit-limit': '1200',
portal  |       'ratelimit-remaining': '1198',
portal  |       'ratelimit-reset': '35',
portal  |       'content-type': 'application/json; charset=utf-8',
portal  |       'content-encoding': 'utf-8',
portal  |       'content-length': '115',
portal  |       etag: 'W/"73-eb0hrd8JxqAFgoAAtD65TJKn7M0"',
portal  |       date: 'Mon, 14 Oct 2024 15:09:01 GMT',
portal  |       connection: 'keep-alive',
portal  |       'keep-alive': 'timeout=5'
portal  |     },
portal  |     body: ReadableStream { locked: true, state: 'closed', supportsBYOB: true },
portal  |     bodyUsed: true,
portal  |     ok: false,
portal  |     redirected: false,
portal  |     type: 'basic',
portal  |     url: 'http://authup:3000/users/@me'
portal  |   },
portal  |   status: 403,
portal  |   statusCode: 403,
portal  |   statusMessage: 'Forbidden',
portal  |   statusText: 'Forbidden',
portal  |   [cause]: undefined
portal  | }
portal  | [nitro] [unhandledRejection] ClientError: The evaluation of permission user_read failed.
portal  |     at handleError (file:///usr/src/app/packages/portal/.output/server/node_modules/hapic/dist/index.mjs:720:23)
portal  |     at Client.request (file:///usr/src/app/packages/portal/.output/server/node_modules/hapic/dist/index.mjs:804:20)
portal  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
portal  |     at async UserInfoAPI.get (file:///usr/src/app/packages/portal/.output/server/node_modules/@hapic/oauth2/dist/index.mjs:338:26)
portal  |     at async resolveInternal (file:///usr/src/app/packages/portal/.output/server/node_modules/@authup/client-web-kit/dist/index.mjs:243:21) {
portal  |   code: undefined,
portal  |   expose: undefined,
portal  |   logMessage: undefined,
portal  |   logLevel: undefined,
portal  |   data: undefined,
portal  |   '@instanceof': Symbol(ClientError),
portal  |   request: {
portal  |     baseURL: 'http://authup:3000/',
portal  |     transform: [ [Function (anonymous)] ],
portal  |     headers: Headers {
portal  |       accept: 'application/json',
portal  |       Authorization: 'Bearer xyz'
portal  |     },
portal  |     method: 'GET',
portal  |     url: 'http://authup:3000/users/@me'
portal  |   },
portal  |   response: Response {
portal  |     status: 403,
portal  |     statusText: 'Forbidden',
portal  |     headers: Headers {
portal  |       vary: 'Origin',
portal  |       'access-control-allow-credentials': 'true',
portal  |       'ratelimit-limit': '1200',
portal  |       'ratelimit-remaining': '1196',
portal  |       'ratelimit-reset': '35',
portal  |       'content-type': 'application/json; charset=utf-8',
portal  |       'content-encoding': 'utf-8',
portal  |       'content-length': '115',
portal  |       etag: 'W/"73-eb0hrd8JxqAFgoAAtD65TJKn7M0"',
portal  |       date: 'Mon, 14 Oct 2024 15:09:01 GMT',
portal  |       connection: 'keep-alive',
portal  |       'keep-alive': 'timeout=5'
portal  |     },
portal  |     body: ReadableStream { locked: true, state: 'closed', supportsBYOB: true },
portal  |     bodyUsed: true,
portal  |     ok: false,
portal  |     redirected: false,
portal  |     type: 'basic',
portal  |     url: 'http://authup:3000/users/@me'
portal  |   },
portal  |   status: 403,
portal  |   statusCode: 403,
portal  |   statusMessage: 'Forbidden',
portal  |   statusText: 'Forbidden',
portal  |   [cause]: undefined
portal  | }
```

**Comment by tada5hi** [comment]
@nr23730 

I have 2 questions about this issue.
-  Does the workflow only not work if a role mapping is defined?
-  I assume that the token in the requests was replaced by you with `xyz`? If so, could you inspect ( https://jwt.io/ )  the token and let me know if the payload fields **sub** and **sub_kind** are set?

Thank you very much

**Comment by nr23730** [comment]
If I define a role mapping in authup for the identity provider, e.g. role `admin` with `Name` and `Value` empty, all users will have admin role on login. 
If I try something different, I'm not able to login anymore. I defined e.g. `admin` as a client role for authup in keycloak. My user has this role assigned. I tried setting `admin/admin` as mapping in authup and the one that you suggested. Both with regex turned on and off.

![image](https://github.com/user-attachments/assets/c991a348-be96-4a50-ae19-529ff444e6fb)

Also: My user appears in the user list after the login attempt. If I manually assign roles here, I'm also not able to login.

Token inspection says that sub and sub_kind are set. sub is an UUID and sub_kind is `user`.

**Comment by tada5hi** [comment]
> If I define a role mapping in authup for the identity provider, e.g. role `admin` with `Name` and `Value` empty, all users will have admin role on login.

That is the intended behavior. The idea behind this is that users who log in with the identity provider are always assigned the role xyz.
However, if you want users who login with the identity provider (e.g. keycloak) to be assigned the role only under certain conditions, then a name and value must be set.

> If I try something different, I'm not able to login anymore. I defined e.g. `admin` as a client role for authup in keycloak. My user has this role assigned. I tried setting `admin/admin` as mapping in authup and the one that you suggested. Both with regex turned on and off.
> 
> ![image](https://private-user-images.githubusercontent.com/20756025/377009512-c991a348-be96-4a50-ae19-529ff444e6fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODMxNDksIm5iZiI6MTcyOTA4Mjg0OSwicGF0aCI6Ii8yMDc1NjAyNS8zNzcwMDk1MTItYzk5MWEzNDgtYmU5Ni00YTUwLWFlMTktNTI5ZmY0NDRlNmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEyNDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYzNlOWVhMjM3YmMwZDYwZjk4ZjM4ZDhlZDllZjczMWVjZDhjODg2OGU1N2NlMzk5OTMxOWJjNjU0YzdkZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y-SxdyTMDIfMA3tsrTnVgaH8aMc_9BFrkf2DeZDvXi0)
> 
> Also: My user appears in the user list after the login attempt. If I manually assign roles here, I'm also not able to login.
> Token inspection says that sub and sub_kind are set. sub is an UUID and sub_kind is `user`.
> 
> I just retested with the most recent version of authup/authup:next. As they change frequently I thought it would be easier if I reference the sha256 sum.

So the login only works if the admin role mapping is set?

**Comment by tada5hi** [comment]
> Three issues: 
> a) Role mapping based on Name/Value in the identity provider of authup does not work. 

I have tested this again myself with a keycloak instance. I don't know if you have assigned a realm or client role to the user in keycloak.
But with the mapping realm_access.role.* and e.g. admin (if there is an admin realm role with corresponding assignment in keycloak) should work.

> b) Login does not work if roles are manually assigned (even admin) in authup 

should be fixed with the latext `next` docker image.

> c) Login does only work when admin role is granted

should be fixed with the latext `next` docker image.

Can you test it again and confirm that the problems no longer exist?

**Comment by nr23730** [comment]
Just tried with `next` image and a), b) and c) are resolved. :partying_face: 

PS: Thanks for fixing this so quickly! :)
