### ISSUE TITLE
Feature: Extend Docs

### ISSUE THREAD

**Issue by tada5hi** [authup/authup#396]
- [ ] general conecpts
- [ ] general workflows ( oauth2, openid)
- [ ] examples ( api interaction )
- [ ] plugin/extension guide for developers

**Comment by Jogai** [comment]
- [ ] How the vue components can be used

?
:wink:

**Comment by tada5hi** [comment]
@Jogai have you read this section https://authup.org/guide/development/javascript-client-vue/ ?

**Comment by Jogai** [comment]
No, missed it. Thanks, that should be it.

**Comment by tada5hi** [comment]
You are welcome ☺️
